### PR TITLE
Fix transforming k8s secrets

### PR DESCRIPTION
**Pull request by mflis**
During the dependencies upgrades, object type of Secrets
 changed from v1.Secret to Unstructured. We need to cast
 it to make secrets.go TransformManifests method work again.

Related: https://github.com/armory/spinnaker-operator/issues/245#issuecomment-1180613717

### CODE REVIEW

**Review by delpic — APPROVED** [review]

**Comment by ichi0915** [comment]
Looks good, I'm going to do some testing to see if this fix works

**Comment by andrijaperovic** [comment]
Built this locally from the fix branch, can confirm it's working correctly on our AKS v1.23.5 cluster. Thanks @mflis !

**Comment by mflis** [comment]
Build failed on "[Login to docker registry](https://github.com/armory/spinnaker-operator/blob/master/.github/workflows/build.yml#L97-L106)" as my fork doesn't have the required secrets. How can we proceed with this MR?

**Review by ichi0915 — APPROVED** [review]

**Comment by ichi0915** [comment]
It's also working for me thank you @mflis, Let me see what we can do to get this merge

**Comment by dogonthehorizon** [comment]
I'm going to merge this on the following criteria:
- Approvals from the community
- Build & unit tests are passing
- The error is related to credentials sharing across orgs (e.g. this PR from a fork can't read our docker creds)

If we have issues w/ the builds on master we can revert and/or review to resolve the behavior. Thanks for the contribution @mflis !

**Comment by ElevateTechUser** [comment]
This PR wasn't build and push to docker registry

**Pull request merged**
